basePath: /api/v1
host: localhost:9000
info:
  contact: {}
  description: This Task Service Swagger.
  title: Swagger Task API
  version: "1.0"
paths:
  /tasks:
    get:
      description: get All tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get Tasks
swagger: "2.0"
